/**
 * Sidebar for the unversioned Serverpod Cloud docs instance.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsCloud = {
  cloudSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: 'Serverpod Framework',
      href: '/',
      className: 'sidebar-mobile-product-switch sidebar-icon-serverpod-framework',
    },
  ],
};

module.exports = sidebarsCloud;
