blank_issues_enabled: false
contact_links:
  - name: Something missing or incorrect?
    url: https://github.com/serverpod/serverpod/issues/new/choose
    about: Please open an issue in the Serverpod repository for documentation corrections or suggestions.
